services:
  django-app:
    build: ./backend-django-master
    container_name: django-app
    command: gunicorn --bind 0.0.0.0:8000 blog.wsgi:application
    volumes:
      - ./backend-django-master:/app
    expose:
      - "8000"  # Expose internally for Nginx to proxy
    environment:
      - DEBUG=True  # Other environment variables if needed
    networks:
      - app-network

  react-app:
    build:
      context: ./frontend-react-main
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - "3000"  # Expose internally for Nginx to proxy
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Publicly expose Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django-app
      - react-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

